---
# tasks file for nginx
- name: Instalando Nginx web server
  apt:
    update_cache: yes
    pkg:
      - nginx

- name: Copiar favicon
  copy:
    src: favicon.ico
    dest: /var/www/html

- name: Copiando archivo index al web server
  template:
    src: index.html.j2
    dest: /var/www/html/index.nginx-debian.html
    #/usr/share/nginx/html/index.html
  notify:
    - Reiniciar Nginx
