all:
  vars:
    ansible_ssh_private_key_file: sshkeys/sshkey
    ansible_user: root

# HAProxy
proxies:
  vars:
    haproxy_width_stats: true
    haproxy_with_auth: true
    haproxy_user: admin
    haproxy_password: 12345

  hosts:
    proxy01:
      ansible_host: 24.144.116.124

# Nginx Servers
webservers:
  hosts:
    nginx-01:
      ansible_host: 208.68.38.157
    nginx-02:
       ansible_host: 159.223.101.36
    # nginx-03:
    #   ansible_host: 192.168.1.249
