version: "3.9"
services:
  mariadb:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
      - MYSQL_DATABASE=workshop
      - MYSQL_ROOT_HOST=%
      - MYSQL_PASSWORD=p@ssw0rd

volumes:
  db_data: